/*
    framework/include/gmsec_version.h file autogenerated on:

    11/20/2010 11:25:35
*/

#ifndef gmsec_version_h
#define gmsec_version_h


#define GMSEC_VERSION "GMSEC API v3.1 [11/20/2010]"

#define OS "Linux 2.6.35-22-generic x86_64"

#define JAVA_VERSION "java version 1.6.0_20"

#define C_PLUS_PLUS_VERSION ""

#endif

