# ===========================================================================
# Project:   FdsDemo
# Copyright: ©2011 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, :flot], :styles => "resources/jquery.jgrowl.css"
